#!/usr/bin/python
import os
import sys

sys.path.insert(0, os.path.dirname(__file__) or '.')
PY_VERSION = 'python-' + ('.'.join(map(str, sys.version_info[:2])))
PY_DIR = os.environ['HOME'] + '/' + PY_VERSION


virtenv = PY_DIR + '/virtenv/'

PY_CACHE = virtenv + 'lib/' + PY_VERSION + '/site-packages'

os.environ['PYTHON_EGG_CACHE'] = os.path.join(PY_CACHE)
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

#~ this is for exclusive usage of Openshift
from mega2 import app as application

